### ISSUE TITLE
DEFAULTS.ini

### ISSUE THREAD

**Issue by IainPerry** [genomehubs/template-plugin#2]
Not sure if this is specific to my fork or just a bug.

Assembly stats and codon usage are /util/:
ASSEMBLY_STATS_URL = http://localhost:8882/util/assembly-stats/assembly-stats.html?path=/v1/json/assemblies/&
CODON_USAGE_URL = http://localhost:8882/util/codon-usage/codon-usage.html?path=/v1/json/annotations/&

but should be changed to /html/ to link.
ASSEMBLY_STATS_URL = http://localhost:8882/html/assembly-stats/assembly-stats.html?path=/v1/json/assemblies/&
CODON_USAGE_URL = http://localhost:8882/html/codon-usage/codon-usage.html?path=/v1/json/annotations/&

**Comment by rjchallis** [comment]
Following your [previous comment](https://github.com/genomehubs/genomehubs/issues/8#issuecomment-494882181) about the downloads container serving `/var/www` instead of `/var/www/html`, I updated the container and moved the assembly stats scripts to a `util` directory. This meant updating the links in this repository to point to a new `utils` directory. This didn't seem to be worth a version bump but as you had followed the previous instructions, you have the older version of the downloads container, which has the same tag as the new version.

You can either keep running the older version with the change you have noted in you plugin, or `docker pull genomehubs/h5ai:19.05` and restart it with the data directory mounted to `/var/www/html`

```
docker run -d \
             --name genomehubs-download \
             -v ~/genomehubs/v1/download/conf:/conf:ro \
             -v ~/genomehubs/v1/download/data:/var/www/html/v1:ro \
             -p 8882:8080 \
             genomehubs/h5ai:19.05
```
